batch_size = 32
epochs = 200
lr = 0.01
momentum = 0.9
no_cuda =False
cuda_id = '2'
seed = 1
log_interval = 10
l2_decay = 5e-4
class_num = 5
param = 0.3
bottle_neck = True
# root_path = "./data/Office31/"
# source_name = "dslr"
# target_name = "amazon"
# source_name = "amazon"
# target_name = "dslr"
root_path = "./DSAN_DATA_mel_2/BC/"
source_name = "B"
target_name = "C"
# root_path = "./DSAN_DATA_spectrum/BC/"
# source_name = "B"
# target_name = "C"